spring:
  application:
    name: store
  Jwt:
    secret: ${JWT_SECRET}
    accessTokenExpiration: 7200 # 2 hours # 300 - seconds in 5 minutes
    refreshTokenExpiration: 86400 # seconds in 1 day
  profiles:
    active: dev
stripe:
  secretKey: ${STRIPE_SECRET_KEY}
  webhookSecretKey: ${STRIPE_WEBHOOK_SECRET_KEY}